---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tvrestoreR

<!-- badges: start -->
<!-- badges: end -->

`tvRestoreR` is an R package for image restoration using total variation (TV) regularization.  
It supports inpainting (filling in missing or masked pixels) and denoising (removing noise from observed pixels) through a single variational framework.  
Using a primal-dual (Chambolle–Pock) solver, the package takes a user-provided image and mask, applies TV regularization with a tuning parameter (λ), and returns a restored image that respects the observed data while enforcing smoothness and preserving edges.


## Work In Progress -- What is Left
So Far: functions for creating and plotting example images, working implementation of restore function. 

What is Left: Complete restore function, gridsearch function on hyperparameters function, add vignette, potentially add more solver methods for the restore function. 


## Installation

You can install the development version of tvrestoreR from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("jaylee0717-dev/tvrestoreR")
```

## Example

